### ISSUE TITLE
Please fix line 197 of boot_cljs_repl.clj

### ISSUE THREAD

**Issue by ikzk** [adzerk-oss/boot-cljs-repl#59]
It seems that otherwise we cannot add middleware (e.g. cider nrepl)

**Comment by Deraen** [comment]
It works already if you use `*default-middleware*`:

```clj
(swap! boot.repl/*default-middleware* into
       '[cider.nrepl/cider-middleware
         refactor-nrepl.middleware/wrap-refactor])
```

Problem is just that you can use `:middleware` option with `cljs-repl` task, but I don't think that would be good practice anyway, at least with cider-nrepl. It is better to configure cider-nrepl and such on your own `~/.boot/profile.boot` instead of project files, as these are user specific.

**Comment by ikzk** [comment]
Thanks!!
